-- 20260613_id_defaults.sql
-- Make the DB the sole owner of bigint primary keys so the client stops minting
-- ids with Date.now() (Tier 2 backlog: "Unify contact ID generation").
--
-- Date.now() ms keys collide when two members of the same client insert in the
-- same millisecond, or across devices with clock skew — possible since RLS
-- enabled multiple members per client.
--
-- Findings (2026-06-13, from information_schema.columns):
--   property_crm_contacts.id  default = nextval('property_crm_contacts_id_seq')
--     -> already sequence-backed; the app's Date.now() has been OVERRIDING it.
--        No schema change needed; just advance the sequence past the existing
--        Date.now()-derived rows so nextval() can't collide, then stop sending id.
--   contact_offers.id         default = null
--     -> genuinely no default; attach an identity sequence.
--
-- Why bigint identity and not UUID: contacts.id is referenced by FKs on the
-- dormant sms_messages / email_messages / *_followup_queue tables. A bigint->uuid
-- change would orphan that historical data with no clean remap.
--
-- Why BY DEFAULT (not ALWAYS) on offers: explicit ids must still insert during the
-- deploy window so a tab on the old (Date.now) bundle doesn't error.

BEGIN;

-- contacts: default already exists; just make the sequence safe. setval marks it
-- "called", so the next nextval() returns MAX(id)+1. Existing Date.now() ids are
-- ~1.7e12, so the sequence simply continues from there (bigint has the headroom).
SELECT setval(
  'property_crm_contacts_id_seq',
  (SELECT COALESCE(MAX(id), 1) FROM property_crm_contacts)
);

-- offers: no default — attach an identity sequence and advance past current max.
ALTER TABLE contact_offers
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
  pg_get_serial_sequence('contact_offers', 'id'),
  (SELECT COALESCE(MAX(id), 1) FROM contact_offers)
);

COMMIT;

-- Verify (run separately after commit):
--   SELECT table_name, column_name, column_default, is_identity
--   FROM information_schema.columns
--   WHERE table_name IN ('property_crm_contacts','contact_offers') AND column_name='id';
--   -> contacts: column_default still nextval(...), is_identity NO (its default works).
--   -> offers:   is_identity YES.

-- Rollback (only if you need to re-run the offers ALTER):
--   ALTER TABLE contact_offers ALTER COLUMN id DROP IDENTITY IF EXISTS;
