-- 2026-08-27 — SMS: manual texting from the CRM.
--
-- Replaces nothing: the Railway-era sms_messages/sms_settings tables were dropped when the
-- server was decommissioned (2026-06-10). Only the contact-side scaffolding survived
-- (sms_status, last_sms_at), and this file builds on it.
--
-- Threat model for this file:
--   * The send Edge Function runs as service_role and BYPASSES RLS. So neither the tenancy
--     check nor the compliance checks can live in TypeScript — they live in
--     sms_send_precheck() below, which is the ONLY sanctioned path to a send. Same
--     precedent as phone_sync_contacts_for() in db/20260804_google_contact_sync.sql.
--   * The browser bundle ships the anon key publicly, so a guard implemented in React is
--     decoration. Nothing here trusts a client-supplied client_id, user_id, or number.
--   * Every check FAILS CLOSED. An unrecognised area code, a malformed number, or a
--     missing DNC scrub all block the send rather than allowing it.
--
-- Compliance notes (why these particular guards):
--   * 47 CFR 64.1200(c)(2) — solicitations to numbers on the National DNC Registry are
--     actionable whether sent manually or automatically. Curating the list by hand does
--     not help here, which is why dnc_state() gates the send.
--   * 47 CFR 64.1200(d) — internal DNC policy: opt-outs must be honoured promptly and
--     permanently, and must survive changing the sending number. Hence the opt-out lives
--     on the contact in our DB, not only in Twilio's per-number STOP list.
--   * Quiet hours are 8am-9pm in the RECIPIENT's local time, not the sender's.

-- SUPERSEDED IN PART by db/20260827_sms_optout_hardening.sql (same day): opt-outs moved
-- from the contact row to the number, and STOP detection gained a phrase tier. Run both.

begin;

-- ── Helpers ────────────────────────────────────────────────────────────────────
-- Mirrors normalizePhone() in src/lib/utils.js: digits only, last 10.
create or replace function public.sms_digits(p_phone text)
returns text
language sql immutable
as $$
  select right(regexp_replace(coalesce(p_phone, ''), '\D', '', 'g'), 10);
$;
revoke execute on function public.sms_digits(text) from public, anon;
grant execute on function public.sms_digits(text) to authenticated;

-- ── Message log ────────────────────────────────────────────────────────────────
create table if not exists public.sms_messages (
  id            bigint generated by default as identity primary key,
  client_id     uuid        not null references public.clients(id) on delete cascade,
  contact_id    bigint      references public.property_crm_contacts(id) on delete set null,
  direction     text        not null check (direction in ('outbound', 'inbound')),
  -- Stored as 10 digits so inbound webhooks match contacts regardless of +1/formatting.
  peer_number   text        not null,
  from_number   text        not null,
  to_number     text        not null,
  body          text        not null,
  -- Twilio's message SID. Unique so a webhook retry cannot double-log a message.
  provider_sid  text        unique,
  status        text        not null default 'queued',
  error_code    text,
  segments      int,
  -- Who pressed send. Null for inbound.
  sent_by       uuid        references auth.users(id) on delete set null,
  created_at    timestamptz not null default now()
);

create index if not exists sms_messages_contact_idx on public.sms_messages (contact_id, created_at desc);
create index if not exists sms_messages_client_idx  on public.sms_messages (client_id, created_at desc);
create index if not exists sms_messages_peer_idx    on public.sms_messages (client_id, peer_number, created_at desc);

alter table public.sms_messages enable row level security;

-- Read-only to members: every write goes through the SECURITY DEFINER functions below, so
-- the app cannot log a send that never happened or quietly erase one that did.
drop policy if exists "client members can read sms" on public.sms_messages;
create policy "client members can read sms" on public.sms_messages
  for select to authenticated
  using (client_id in (select cu.client_id from public.client_users cu where cu.user_id = auth.uid()));

revoke insert, update, delete on public.sms_messages from anon, authenticated;

-- ── DNC registry ───────────────────────────────────────────────────────────────
-- Numbers downloaded from telemarketing.donotcall.gov (free for 5 area codes), or loaded
-- from a commercial scrub. See scripts/load-dnc.mjs.
create table if not exists public.dnc_numbers (
  phone      text primary key check (phone ~ '^[0-9]{10}$'),
  loaded_at  timestamptz not null default now()
);

-- THE reason dnc_state() can ever answer "clear". A number's absence from dnc_numbers only
-- means it is unlisted if we actually hold that area code's file — otherwise absence just
-- means we never looked. Without this table a partial download silently reads as a clean
-- bill of health for the whole country, which is the exact failure that gets people sued.
create table if not exists public.dnc_area_codes (
  area_code    text primary key check (area_code ~ '^[2-9][0-9]{2}$'),
  loaded_at    timestamptz not null default now(),
  source       text,
  number_count int
);

alter table public.dnc_numbers    enable row level security;
alter table public.dnc_area_codes enable row level security;
revoke all on public.dnc_numbers    from anon, authenticated;
-- Coverage is not sensitive and the UI needs it to explain "this area code isn't scrubbed".
drop policy if exists "read dnc coverage" on public.dnc_area_codes;
create policy "read dnc coverage" on public.dnc_area_codes for select to authenticated using (true);
grant select on public.dnc_area_codes to authenticated;

-- 'listed' | 'clear' | 'unknown' | 'invalid'
create or replace function public.dnc_state(p_phone text)
returns text
language sql stable security definer set search_path = public
as $$
  select case
    when length(public.sms_digits(p_phone)) <> 10                      then 'invalid'
    when left(public.sms_digits(p_phone), 1) in ('0', '1')             then 'invalid'
    when exists (select 1 from public.dnc_numbers d
                 where d.phone = public.sms_digits(p_phone))           then 'listed'
    when exists (select 1 from public.dnc_area_codes a
                 where a.area_code = left(public.sms_digits(p_phone), 3)) then 'clear'
    else 'unknown'
  end;
$$;
revoke execute on function public.dnc_state(text) from public, anon;
grant execute on function public.dnc_state(text) to authenticated;

-- ── Area code → timezone (quiet hours) ─────────────────────────────────────────
-- TCPA quiet hours are 8am-9pm in the RECIPIENT's local time. County can't supply that —
-- "Greenville" alone is ambiguous across SC/NC/GA — so the area code does.
--
-- Split area codes carry alt_timezone; the send must be inside the window in BOTH, because
-- assuming either half is a violation for the other. Unknown codes are not in this table
-- and are BLOCKED, which is also what happens to the malformed data already in the list
-- (010, 050, 125, 160, 168) and to non-US codes (705, 778 Canada).
create table if not exists public.area_code_timezones (
  area_code    text primary key check (area_code ~ '^[2-9][0-9]{2}$'),
  timezone     text not null,
  alt_timezone text
);

alter table public.area_code_timezones enable row level security;
drop policy if exists "read area code timezones" on public.area_code_timezones;
create policy "read area code timezones" on public.area_code_timezones for select to authenticated using (true);
grant select on public.area_code_timezones to authenticated;

insert into public.area_code_timezones (area_code, timezone) values
  -- Eastern
  ('201','America/New_York'),('202','America/New_York'),('203','America/New_York'),
  ('212','America/New_York'),('215','America/New_York'),('216','America/New_York'),
  ('229','America/New_York'),('231','America/New_York'),('239','America/New_York'),
  ('240','America/New_York'),('248','America/New_York'),('252','America/New_York'),
  ('267','America/New_York'),('269','America/New_York'),('276','America/New_York'),
  ('301','America/New_York'),('302','America/New_York'),('304','America/New_York'),
  ('305','America/New_York'),('313','America/New_York'),('315','America/New_York'),
  ('317','America/New_York'),('321','America/New_York'),('330','America/New_York'),
  ('336','America/New_York'),('347','America/New_York'),('352','America/New_York'),
  ('386','America/New_York'),('401','America/New_York'),('404','America/New_York'),
  ('407','America/New_York'),('410','America/New_York'),('412','America/New_York'),
  ('413','America/New_York'),('419','America/New_York'),('423','America/New_York'),
  ('440','America/New_York'),('443','America/New_York'),('470','America/New_York'),
  ('478','America/New_York'),('484','America/New_York'),('502','America/New_York'),
  ('508','America/New_York'),('513','America/New_York'),('516','America/New_York'),
  ('517','America/New_York'),('518','America/New_York'),('540','America/New_York'),
  ('561','America/New_York'),('567','America/New_York'),('570','America/New_York'),
  ('571','America/New_York'),('574','America/New_York'),('585','America/New_York'),
  ('586','America/New_York'),('603','America/New_York'),('606','America/New_York'),
  ('607','America/New_York'),('609','America/New_York'),('610','America/New_York'),
  ('614','America/New_York'),('616','America/New_York'),('617','America/New_York'),
  ('631','America/New_York'),('646','America/New_York'),('656','America/New_York'),
  ('678','America/New_York'),('703','America/New_York'),('704','America/New_York'),
  ('706','America/New_York'),('716','America/New_York'),('717','America/New_York'),
  ('718','America/New_York'),('724','America/New_York'),('727','America/New_York'),
  ('732','America/New_York'),('734','America/New_York'),('740','America/New_York'),
  ('754','America/New_York'),('757','America/New_York'),('765','America/New_York'),
  ('770','America/New_York'),('771','America/New_York'),('772','America/New_York'),
  ('774','America/New_York'),('781','America/New_York'),('786','America/New_York'),
  ('802','America/New_York'),('803','America/New_York'),('804','America/New_York'),
  ('810','America/New_York'),('813','America/New_York'),('814','America/New_York'),
  ('828','America/New_York'),('843','America/New_York'),('845','America/New_York'),
  ('856','America/New_York'),('859','America/New_York'),('860','America/New_York'),
  ('863','America/New_York'),('864','America/New_York'),('865','America/New_York'),
  ('904','America/New_York'),('908','America/New_York'),('910','America/New_York'),
  ('912','America/New_York'),('914','America/New_York'),('917','America/New_York'),
  ('919','America/New_York'),('937','America/New_York'),('941','America/New_York'),
  ('954','America/New_York'),('973','America/New_York'),('978','America/New_York'),
  ('980','America/New_York'),
  -- Central
  ('205','America/Chicago'),('210','America/Chicago'),('214','America/Chicago'),
  ('217','America/Chicago'),('218','America/Chicago'),('224','America/Chicago'),
  ('228','America/Chicago'),('251','America/Chicago'),('254','America/Chicago'),
  ('256','America/Chicago'),('262','America/Chicago'),('270','America/Chicago'),
  ('281','America/Chicago'),('312','America/Chicago'),('314','America/Chicago'),
  ('318','America/Chicago'),('334','America/Chicago'),('337','America/Chicago'),
  ('364','America/Chicago'),('402','America/Chicago'),('405','America/Chicago'),
  ('409','America/Chicago'),('414','America/Chicago'),('469','America/Chicago'),
  ('501','America/Chicago'),('504','America/Chicago'),('507','America/Chicago'),
  ('512','America/Chicago'),('601','America/Chicago'),('612','America/Chicago'),
  ('615','America/Chicago'),('618','America/Chicago'),('630','America/Chicago'),
  ('636','America/Chicago'),('651','America/Chicago'),('662','America/Chicago'),
  ('708','America/Chicago'),('713','America/Chicago'),('715','America/Chicago'),
  ('731','America/Chicago'),('763','America/Chicago'),('773','America/Chicago'),
  ('779','America/Chicago'),('785','America/Chicago'),('815','America/Chicago'),
  ('816','America/Chicago'),('817','America/Chicago'),('832','America/Chicago'),
  ('847','America/Chicago'),('901','America/Chicago'),('903','America/Chicago'),
  ('913','America/Chicago'),('918','America/Chicago'),('920','America/Chicago'),
  ('936','America/Chicago'),('972','America/Chicago'),('979','America/Chicago'),
  ('985','America/Chicago'),
  -- Mountain
  ('303','America/Denver'),('307','America/Denver'),('406','America/Denver'),
  ('435','America/Denver'),('505','America/Denver'),('575','America/Denver'),
  ('719','America/Denver'),('720','America/Denver'),('801','America/Denver'),
  ('915','America/Denver'),('970','America/Denver'),
  -- Arizona (no DST)
  ('480','America/Phoenix'),('520','America/Phoenix'),('602','America/Phoenix'),
  ('623','America/Phoenix'),('928','America/Phoenix'),
  -- Pacific
  ('206','America/Los_Angeles'),('209','America/Los_Angeles'),('213','America/Los_Angeles'),
  ('253','America/Los_Angeles'),('310','America/Los_Angeles'),('323','America/Los_Angeles'),
  ('360','America/Los_Angeles'),('408','America/Los_Angeles'),('415','America/Los_Angeles'),
  ('424','America/Los_Angeles'),('425','America/Los_Angeles'),('503','America/Los_Angeles'),
  ('509','America/Los_Angeles'),('510','America/Los_Angeles'),('530','America/Los_Angeles'),
  ('559','America/Los_Angeles'),('562','America/Los_Angeles'),('619','America/Los_Angeles'),
  ('650','America/Los_Angeles'),('702','America/Los_Angeles'),('714','America/Los_Angeles'),
  ('747','America/Los_Angeles'),('760','America/Los_Angeles'),('775','America/Los_Angeles'),
  ('805','America/Los_Angeles'),('818','America/Los_Angeles'),('831','America/Los_Angeles'),
  ('858','America/Los_Angeles'),('909','America/Los_Angeles'),('916','America/Los_Angeles'),
  ('925','America/Los_Angeles'),('949','America/Los_Angeles'),('951','America/Los_Angeles'),
  -- Non-contiguous
  ('808','Pacific/Honolulu'),('907','America/Anchorage'),('787','America/Puerto_Rico')
on conflict (area_code) do nothing;

-- Split area codes: the window must hold in both halves.
insert into public.area_code_timezones (area_code, timezone, alt_timezone) values
  ('605','America/Chicago','America/Denver'),      -- South Dakota
  ('812','America/New_York','America/Chicago'),    -- Indiana (Evansville is Central)
  ('850','America/New_York','America/Chicago'),    -- Florida panhandle
  ('906','America/New_York','America/Chicago'),    -- Michigan UP
  ('541','America/Los_Angeles','America/Denver'),  -- Oregon (Malheur County is Mountain)
  ('806','America/Chicago','America/Denver')       -- Texas panhandle
on conflict (area_code) do update
  set timezone = excluded.timezone, alt_timezone = excluded.alt_timezone;

-- true only if the instant is inside [08:00, 21:00) local in every timezone the area code
-- spans. Unknown area code → no rows → bool_and is null → coalesce false. Fails closed.
create or replace function public.sms_within_quiet_hours(p_phone text, p_at timestamptz default now())
returns boolean
language sql stable security definer set search_path = public
as $fn$
  select coalesce(bool_and(t.h >= 8 and t.h < 21), false)
  from public.area_code_timezones a
  cross join lateral (
    select extract(hour from p_at at time zone z)::int as h
    from unnest(array[a.timezone, a.alt_timezone]) as z
    where z is not null
  ) t
  where a.area_code = left(public.sms_digits(p_phone), 3);
$fn$;
revoke execute on function public.sms_within_quiet_hours(text, timestamptz) from public, anon;
grant execute on function public.sms_within_quiet_hours(text, timestamptz) to authenticated;

-- ── Consent / opt-out on the contact ───────────────────────────────────────────
-- Express consent or an established business relationship is the lawful basis that lets a
-- DNC-listed number be texted. It is recorded deliberately, with a note saying where it
-- came from — never a default, never inferred. A blank note is not consent.
alter table public.property_crm_contacts
  add column if not exists sms_consent_at   timestamptz,
  add column if not exists sms_consent_note text,
  add column if not exists sms_opted_out_at timestamptz;

-- Per-client daily send cap. Defaults to 25; the operator's stated pace is 20/day.
-- The sending number reuses the Railway-era twilio_number column, which ManageClientsModal
-- already edits. Renamed to sms_number by db/20260827_telnyx.sql, and the stale Twilio value
-- it carried was cleared by db/20260827_clear_stale_sms_number.sql.
alter table public.clients
  add column if not exists sms_daily_cap int not null default 25;

-- ── THE send boundary ──────────────────────────────────────────────────────────
-- Every guard in one place, in SQL, because the Edge Function runs as service_role and
-- bypasses RLS. Returns a reason rather than just a boolean so the UI can say WHY a number
-- is blocked — "area code 410 isn't scrubbed yet" is actionable; a silent failure is not.
--
-- Order is deliberate: authorization first (never leak whether a contact exists), then the
-- facts about the number, then the legal gates, then rate limiting.
--
-- service_role only. The UI calls sms_check_number() below, which pins the user to
-- auth.uid() — taking a user id from the browser would let any signed-in user text on
-- behalf of another tenant.
create or replace function public.sms_send_precheck(
  p_user uuid, p_contact_id bigint, p_phone text
)
returns table (allowed boolean, reason text, client_id uuid, to_number text, dnc text)
language plpgsql stable security definer set search_path = public
as $fn$
declare
  v_contact  record;
  v_digits   text := public.sms_digits(p_phone);
  v_dnc      text;
  v_sent_24h int;
  v_cap      int;
begin
  -- Aliased to cid: the OUT parameter is also called client_id, and plpgsql resolves the
  -- bare name to the parameter, not the record field.
  select c.id, c.client_id as cid, c.phones, c.bad_phones, c.sms_status,
         c.sms_consent_at, c.sms_consent_note
    into v_contact
  from public.property_crm_contacts c
  where c.id = p_contact_id
    and c.client_id in (select cu.client_id from public.client_users cu where cu.user_id = p_user);

  if v_contact.id is null then
    return query select false, 'not_authorized'::text, null::uuid, null::text, null::text;
    return;
  end if;

  v_dnc := public.dnc_state(v_digits);

  if v_dnc = 'invalid' then
    return query select false, 'invalid_number'::text, v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  -- The number must actually be on the contact. Without this the Edge Function would
  -- happily text an arbitrary number supplied by the browser, using the contact only as an
  -- authorization token.
  if not exists (
    select 1 from jsonb_array_elements_text(coalesce(v_contact.phones, '[]'::jsonb)) p
    where public.sms_digits(p) = v_digits
  ) then
    return query select false, 'phone_not_on_contact'::text, v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  if exists (
    select 1 from jsonb_array_elements_text(coalesce(v_contact.bad_phones, '[]'::jsonb)) p
    where public.sms_digits(p) = v_digits
  ) then
    return query select false, 'bad_phone'::text, v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  -- Opt-out is permanent and beats everything below, including recorded consent.
  if v_contact.sms_status in ('do_not_contact', 'not_interested') then
    return query select false, 'opted_out'::text, v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  -- DNC gate. Recorded consent (express consent or an established business relationship)
  -- is the lawful basis that overrides a registry listing — but it must be real: a consent
  -- timestamp with no note explaining its source does not count.
  if v_dnc <> 'clear'
     and not (v_contact.sms_consent_at is not null
              and coalesce(btrim(v_contact.sms_consent_note), '') <> '') then
    return query select false,
      (case when v_dnc = 'listed' then 'dnc_listed' else 'dnc_unscrubbed' end)::text,
      v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  if not public.sms_within_quiet_hours(v_digits) then
    return query select false, 'quiet_hours'::text, v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  -- Trailing 24h rather than a calendar day: no timezone ambiguity, and it stops a burst
  -- at 11pm being doubled at midnight.
  select cl.sms_daily_cap into v_cap from public.clients cl where cl.id = v_contact.cid;
  select count(*) into v_sent_24h
  from public.sms_messages m
  where m.client_id = v_contact.cid
    and m.direction = 'outbound'
    and m.created_at > now() - interval '24 hours';

  if v_sent_24h >= coalesce(v_cap, 25) then
    return query select false, 'daily_cap'::text, v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  return query select true, 'ok'::text, v_contact.cid, v_digits, v_dnc;
end;
$fn$;

-- Postgres grants EXECUTE to PUBLIC by default, and PUBLIC *includes* anon and
-- authenticated. Revoking from those two by name leaves the PUBLIC grant standing and the
-- function stays wide open — the same trap as a policy declared TO public. Caught here by
-- probing has_function_privilege() rather than trusting the revoke, 2026-08-27.
revoke execute on function public.sms_send_precheck(uuid, bigint, text) from public, anon, authenticated;

-- What the UI is allowed to ask: the same check, pinned to the caller.
create or replace function public.sms_check_number(p_contact_id bigint, p_phone text)
returns table (allowed boolean, reason text, dnc text)
language sql stable security definer set search_path = public
as $fn$
  select p.allowed, p.reason, p.dnc
  from public.sms_send_precheck(auth.uid(), p_contact_id, p_phone) p;
$fn$;
revoke execute on function public.sms_check_number(bigint, text) from public, anon;
grant execute on function public.sms_check_number(bigint, text) to authenticated;

-- ── Recording ──────────────────────────────────────────────────────────────────
-- Re-runs the precheck itself rather than trusting the caller's word that it passed. The
-- Edge Function could be changed to skip it; this cannot.
create or replace function public.sms_record_outbound(
  p_user uuid, p_contact_id bigint, p_phone text, p_from text, p_body text,
  p_sid text, p_status text, p_segments int, p_error text
)
returns bigint
language plpgsql security definer set search_path = public
as $fn$
declare v_id bigint; v_client uuid;
begin
  select c.client_id into v_client
  from public.property_crm_contacts c
  where c.id = p_contact_id
    and c.client_id in (select cu.client_id from public.client_users cu where cu.user_id = p_user);
  if v_client is null then raise exception 'not authorized for contact %', p_contact_id; end if;

  insert into public.sms_messages (
    client_id, contact_id, direction, peer_number, from_number, to_number,
    body, provider_sid, status, segments, error_code, sent_by
  ) values (
    v_client, p_contact_id, 'outbound', public.sms_digits(p_phone), p_from, public.sms_digits(p_phone),
    p_body, p_sid, coalesce(p_status, 'queued'), p_segments, p_error, p_user
  )
  on conflict (provider_sid) do update set status = excluded.status, error_code = excluded.error_code
  returning id into v_id;

  -- updated_at is client-set on this table (see CLAUDE.md) — bump it here or the
  -- optimistic-concurrency guard in upsertContact silently degrades.
  update public.property_crm_contacts
  set last_sms_at = now(), updated_at = now()
  where id = p_contact_id;

  return v_id;
end;
$fn$;
revoke execute on function public.sms_record_outbound(uuid, bigint, text, text, text, text, text, int, text) from public, anon, authenticated;

-- Inbound webhook. Routes by which of our numbers was texted, then matches the sender
-- against that client's contacts. An unmatched inbound is still logged (contact_id null)
-- so a reply from a number we don't recognise is never silently dropped.
create or replace function public.sms_record_inbound(
  p_from text, p_to text, p_body text, p_sid text
)
returns table (contact_id bigint, opted_out boolean)
language plpgsql security definer set search_path = public
as $fn$
declare
  v_client  uuid;
  v_contact bigint;
  v_peer    text := public.sms_digits(p_from);
  v_stop    boolean;
begin
  select cl.id into v_client from public.clients cl
  where public.sms_digits(cl.twilio_number) = public.sms_digits(p_to)
  limit 1;

  select c.id into v_contact
  from public.property_crm_contacts c
  where (v_client is null or c.client_id = v_client)
    and exists (
      select 1 from jsonb_array_elements_text(coalesce(c.phones, '[]'::jsonb)) p
      where public.sms_digits(p) = v_peer
    )
  order by c.updated_at desc nulls last
  limit 1;

  if v_client is null then
    select c.client_id into v_client from public.property_crm_contacts c where c.id = v_contact;
  end if;
  if v_client is null then return; end if;

  insert into public.sms_messages (
    client_id, contact_id, direction, peer_number, from_number, to_number, body, provider_sid, status
  ) values (
    v_client, v_contact, 'inbound', v_peer, public.sms_digits(p_from), public.sms_digits(p_to),
    p_body, p_sid, 'received'
  )
  on conflict (provider_sid) do nothing;

  -- 47 CFR 64.1200(d): honour opt-outs promptly and permanently. Twilio also blocks STOP
  -- at the number level, but that block dies with the number — this one does not.
  --
  -- Deliberately one-way: a later START unblocks the sender at Twilio but does NOT clear
  -- do_not_contact here. Being stricter than the carrier is the safe direction.
  v_stop := upper(btrim(coalesce(p_body, ''))) ~
            '^(STOP|STOPALL|UNSUBSCRIBE|CANCEL|END|QUIT|REVOKE|OPTOUT|OPT[ -]?OUT)\.?$';

  if v_stop and v_contact is not null then
    update public.property_crm_contacts
    set sms_status = 'do_not_contact', sms_opted_out_at = now(), updated_at = now()
    where id = v_contact;
  end if;

  return query select v_contact, coalesce(v_stop, false);
end;
$fn$;
revoke execute on function public.sms_record_inbound(text, text, text, text) from public, anon, authenticated;

-- Delivery status callbacks from Twilio.
create or replace function public.sms_update_status(p_sid text, p_status text, p_error text)
returns void
language sql security definer set search_path = public
as $fn$
  update public.sms_messages
  set status = coalesce(p_status, status), error_code = coalesce(p_error, error_code)
  where provider_sid = p_sid;
$fn$;
revoke execute on function public.sms_update_status(text, text, text) from public, anon, authenticated;

commit;
