-- 2026-08-28 — SMS inbox, unread-gating, broadened STOP detection, HELP auto-reply.
--
-- Four changes, all of them serving one property: a reply that asks us to stop must never
-- be lost, and must never be followed by another text.
--
--   1. read_at on sms_messages + an inbox, because an inbound message that nobody reads is
--      the same as an inbound message we never received. Before this, NOTHING outside the
--      per-contact Messages tab read sms_messages: a reply arrived and the operator learned
--      about it only by happening to open that contact.
--
--   2. sms_send_precheck() now BLOCKS on an unread inbound message from the same number.
--      This is the structural fix for the weakest link in the compliance model. STOP
--      detection is text matching and text matching is best-effort; a human reading the
--      reply is not. Blocking until the reply is read converts "we hope the regex caught
--      it" into "a person saw it", which is what 47 CFR 64.1200(d) actually expects.
--
--   3. sms_is_stop() widened. The old matcher missed "please stop." (tier 1 is anchored,
--      tier 2 required an object like "stop texting"), "remove me" without off/from, and
--      "wrong number" — which is a stop request in every way that matters.
--
--   4. sms_record_inbound() never drops a message. It used to return early when it could
--      not resolve a client, discarding the body; the opt-out survived but the message did
--      not. Now it falls back to outbound history and, failing everything, dead-letters to
--      sms_unrouted rather than dropping.
--
-- Depends on: db/20260827_sms.sql, db/20260827_sms_optout_hardening.sql, db/20260827_telnyx.sql

begin;

-- ── 1. Read state ──────────────────────────────────────────────────────────────
alter table public.sms_messages add column if not exists read_at timestamptz;

-- Outbound messages are authored here, so they are read by definition. Only inbound can be
-- unread, and only unread rows are ever scanned — hence the partial index.
update public.sms_messages set read_at = created_at where direction = 'outbound' and read_at is null;

create index if not exists sms_messages_unread_idx
  on public.sms_messages (client_id, peer_number)
  where direction = 'inbound' and read_at is null;

-- ── Dead letter ────────────────────────────────────────────────────────────────
-- An inbound message we cannot attribute to a client. sms_messages.client_id is NOT NULL
-- and RLS is client-scoped, so there is nowhere in that table to put one. Dropping it was
-- the old behaviour and is the thing this file exists to stop.
create table if not exists public.sms_unrouted (
  id          bigint generated by default as identity primary key,
  from_number text        not null,
  to_number   text        not null,
  body        text        not null,
  provider_sid text       unique,
  was_stop    boolean     not null default false,
  created_at  timestamptz not null default now()
);

alter table public.sms_unrouted enable row level security;
revoke all on public.sms_unrouted from anon, authenticated;

-- Visible to anyone who belongs to any client. These rows are by definition un-attributable,
-- so there is no tenant to scope them to; the alternative is that nobody sees them at all.
drop policy if exists "members read unrouted" on public.sms_unrouted;
create policy "members read unrouted" on public.sms_unrouted
  for select to authenticated
  using (exists (select 1 from public.client_users cu where cu.user_id = auth.uid()));
grant select on public.sms_unrouted to authenticated;

-- ── 2. STOP detection, widened ─────────────────────────────────────────────────
-- Deliberately over-matches. A false positive costs one lead; a false negative is a TCPA
-- claim. The backstop for the remainder is the unread-reply block in sms_send_precheck().
--
-- Note what is NOT here: a bare \bstop\b. "You can stop by the property any time" is a
-- sentence this business actually sends and receives, so bare STOP is matched only when it
-- is the whole message or ends it.
create or replace function public.sms_is_stop(p_body text)
returns boolean
language sql immutable
as $$
  select
    -- Tier 1 — exact carrier keywords, the whole message.
    btrim(coalesce(p_body, '')) ~*
      '^\s*(stop|stopall|stop\s+all|unsubscribe|cancel|end|quit|revoke|optout|opt[\s-]?out)\s*[.!]*\s*$'
    -- Tier 2 — "stop" as the end of a sentence, with or without please. Catches
    -- "please stop." and "ok stop", which tier 1 anchors past and the old tier 3 missed
    -- because it demanded an object ("stop texting").
    or coalesce(p_body, '') ~*
      '(^|[^a-z])(please\s+)?stop(\s+(it|now|please|already))?\s*[.!]*\s*$'
    -- Tier 3 — phrases. People write sentences, not keywords.
    or coalesce(p_body, '') ~* (
      '(stop\s+(texting|messaging|contacting|calling|sending|msg)'
      || '|quit\s+(texting|messaging|contacting)'
      || '|unsubscribe|opt\s+me\s+out'
      -- "remove me", "take my number off", "take me off your list" — the old version
      -- required me + off/from and so missed the bare and the possessive forms.
      || '|(remove|take)\s+(me|my\s+(number|name|info|information))\s*(off|from|out)?'
      || '|delete\s+my\s+(number|info|information|contact)'
      || '|do\s*n[o'']?t\s+(text|contact|message|msg|call|reach)\s+(me|us)'
      || '|(never|no\s+longer)\s+(text|contact|message|msg|call)\s+(me|us)'
      || '|no\s+more\s+(text|message|msg|calls?)'
      || '|leave\s+(me|us)\s+alone'
      || '|lose\s+my\s+number'
      -- A wrong number is a request to stop texting that number, whatever else it is.
      || '|wrong\s+(number|#)'
      || '|not\s+interested'
      || '|stop\s+bothering'
      || ')');
$$;

-- ── HELP ───────────────────────────────────────────────────────────────────────
-- CTIA Messaging Principles require HELP to be answered on a 10DLC campaign, and Telnyx —
-- unlike Twilio — sends no automatic reply. Rarely typed, cheap to honour, and it is what
-- the registered campaign says we do.
create or replace function public.sms_is_help(p_body text)
returns boolean
language sql immutable
as $$
  select btrim(coalesce(p_body, '')) ~* '^\s*(help|info|support)\s*[.!?]*\s*$'
      or coalesce(p_body, '')       ~* '(who\s+is\s+this|who\s+are\s+you|what\s+is\s+this)';
$$;

revoke execute on function public.sms_is_help(text) from public, anon;
grant execute on function public.sms_is_help(text) to authenticated;

commit;

begin;

-- Per-client HELP text. Null falls back to a generic reply built from the client name.
alter table public.clients add column if not exists sms_help_text text;

-- ── 3. Inbound recording — never drops a message ───────────────────────────────
-- Return type changes (adds help_reply / reply_from), so the old signature must go first.
drop function if exists public.sms_record_inbound(text, text, text, text);

create or replace function public.sms_record_inbound(
  p_from text, p_to text, p_body text, p_sid text
)
returns table (
  contact_id       bigint,
  opted_out        boolean,
  contacts_stopped integer,
  -- Text the Edge Function should send back, or null. Decided here rather than in
  -- TypeScript so the auto-reply obeys the same suppression rules as everything else.
  help_reply       text,
  reply_from       text
)
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_client  uuid;
  v_contact bigint;
  v_peer    text := public.sms_digits(p_from);
  v_own     text := public.sms_digits(p_to);
  v_stop    boolean := public.sms_is_stop(p_body);
  v_help    text := null;
  v_from    text := null;
  v_n       int := 0;
begin
  -- Opt-out FIRST, before any routing. An unroutable STOP still has to stop us, so it must
  -- not sit behind a lookup that can fail. Keyed on the number: 295 numbers in this data
  -- sit on more than one contact, and all of them are covered.
  if v_stop then
    insert into public.sms_opt_outs (phone, source, matched_body)
    values (v_peer, 'sms_stop', left(coalesce(p_body, ''), 200))
    on conflict (phone) do nothing;

    update public.property_crm_contacts c
    set sms_status = 'do_not_contact', sms_opted_out_at = now(), updated_at = now()
    where exists (
      select 1 from jsonb_array_elements_text(coalesce(c.phones, '[]'::jsonb)) p
      where public.sms_digits(p) = v_peer
    );
    get diagnostics v_n = row_count;
  end if;

  -- Route: the number it came to, then the contact it came from, then who last texted them.
  select cl.id into v_client from public.clients cl
  where public.sms_digits(cl.sms_number) = v_own
  limit 1;

  select c.id into v_contact
  from public.property_crm_contacts c
  where (v_client is null or c.client_id = v_client)
    and exists (
      select 1 from jsonb_array_elements_text(coalesce(c.phones, '[]'::jsonb)) p
      where public.sms_digits(p) = v_peer
    )
  order by c.updated_at desc nulls last
  limit 1;

  if v_client is null and v_contact is not null then
    select c.client_id into v_client from public.property_crm_contacts c where c.id = v_contact;
  end if;

  -- Last resort before the dead letter: whoever last sent to this number. Covers a client
  -- whose sms_number was changed or cleared after the outbound went out.
  if v_client is null then
    select m.client_id into v_client
    from public.sms_messages m
    where m.peer_number = v_peer and m.direction = 'outbound'
    order by m.created_at desc
    limit 1;
  end if;

  if v_client is null then
    -- Un-attributable. Store it anyway — that is the whole point of the table.
    insert into public.sms_unrouted (from_number, to_number, body, provider_sid, was_stop)
    values (v_peer, v_own, p_body, p_sid, v_stop)
    on conflict (provider_sid) do nothing;
    return query select null::bigint, v_stop, v_n, null::text, null::text;
    return;
  end if;

  insert into public.sms_messages (
    client_id, contact_id, direction, peer_number, from_number, to_number, body, provider_sid, status
  ) values (
    v_client, v_contact, 'inbound', v_peer, v_peer, v_own, p_body, p_sid, 'received'
  )
  on conflict (provider_sid) do nothing;

  -- HELP: answer once per number per day, and never to someone who just opted out — an
  -- extra message to a person who asked us to stop is the wrong instinct even where the
  -- carrier would allow it. Auto-replies are the only outbound rows with sent_by null,
  -- which is also how the once-a-day guard recognises them.
  if not v_stop
     and public.sms_is_help(p_body)
     and not exists (select 1 from public.sms_opt_outs o where o.phone = v_peer)
     and not exists (
       select 1 from public.sms_messages m
       where m.peer_number = v_peer and m.direction = 'outbound' and m.sent_by is null
         and m.created_at > now() - interval '24 hours'
     )
  then
    select coalesce(
             nullif(btrim(cl.sms_help_text), ''),
             cl.name || ': we buy land. Reply STOP to opt out.'
           ),
           public.sms_digits(cl.sms_number)
      into v_help, v_from
    from public.clients cl where cl.id = v_client;
  end if;

  return query select v_contact, v_stop, v_n, v_help, v_from;
end;
$function$;

-- ── 4. The unread-reply block ──────────────────────────────────────────────────
create or replace function public.sms_send_precheck(p_user uuid, p_contact_id bigint, p_phone text)
returns table (allowed boolean, reason text, client_id uuid, to_number text, dnc text)
language plpgsql stable security definer set search_path to 'public'
as $function$
declare
  v_contact  record;
  v_digits   text := public.sms_digits(p_phone);
  v_dnc      text;
  v_sent_24h int;
  v_cap      int;
begin
  select c.id, c.client_id as cid, c.phones, c.bad_phones, c.sms_status,
         c.sms_consent_at, c.sms_consent_note
    into v_contact
  from public.property_crm_contacts c
  where c.id = p_contact_id
    and c.client_id in (select cu.client_id from public.client_users cu where cu.user_id = p_user);

  if v_contact.id is null then
    return query select false, 'not_authorized'::text, null::uuid, null::text, null::text;
    return;
  end if;

  v_dnc := public.dnc_state(v_digits);

  if v_dnc = 'invalid' then
    return query select false, 'invalid_number'::text, v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  if not exists (
    select 1 from jsonb_array_elements_text(coalesce(v_contact.phones, '[]'::jsonb)) p
    where public.sms_digits(p) = v_digits
  ) then
    return query select false, 'phone_not_on_contact'::text, v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  if exists (
    select 1 from jsonb_array_elements_text(coalesce(v_contact.bad_phones, '[]'::jsonb)) p
    where public.sms_digits(p) = v_digits
  ) then
    return query select false, 'bad_phone'::text, v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  -- Opt-out, at the NUMBER level and BEFORE the consent branch. Nothing later in this
  -- function reverses it: recorded consent does not resurrect someone who asked us to
  -- stop, and another contact row carrying the same number gets no second chance.
  if exists (select 1 from public.sms_opt_outs o where o.phone = v_digits) then
    return query select false, 'opted_out'::text, v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  if v_contact.sms_status in ('do_not_contact', 'not_interested') then
    return query select false, 'opted_out'::text, v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  -- An unread reply blocks the next send. sms_is_stop() is a regex, and a regex will always
  -- miss some way of saying "go away"; a person reading the message will not. This turns
  -- best-effort matching into a human-in-the-loop guarantee, and it costs the operator one
  -- click — opening the thread marks it read. It sits ABOVE the consent branch for the same
  -- reason the opt-out check does.
  if exists (
    select 1 from public.sms_messages m
    where m.client_id = v_contact.cid
      and m.peer_number = v_digits
      and m.direction = 'inbound'
      and m.read_at is null
  ) then
    return query select false, 'unread_reply'::text, v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  if v_dnc <> 'clear'
     and not (v_contact.sms_consent_at is not null
              and coalesce(btrim(v_contact.sms_consent_note), '') <> '') then
    return query select false,
      (case when v_dnc = 'listed' then 'dnc_listed' else 'dnc_unscrubbed' end)::text,
      v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  if not public.sms_within_quiet_hours(v_digits) then
    return query select false, 'quiet_hours'::text, v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  select cl.sms_daily_cap into v_cap from public.clients cl where cl.id = v_contact.cid;
  select count(*) into v_sent_24h
  from public.sms_messages m
  where m.client_id = v_contact.cid
    and m.direction = 'outbound'
    and m.created_at > now() - interval '24 hours';

  if v_sent_24h >= coalesce(v_cap, 25) then
    return query select false, 'daily_cap'::text, v_contact.cid, v_digits, v_dnc;
    return;
  end if;

  return query select true, 'ok'::text, v_contact.cid, v_digits, v_dnc;
end;
$function$;

-- ── 5. The inbox ───────────────────────────────────────────────────────────────
-- One row per inbound message, newest first, with the contact it matched (if any) and
-- whether the number is already suppressed. Un-matched replies are the reason this is an
-- RPC rather than a PostgREST select against sms_messages: contact_id is null on those,
-- so no per-contact query can ever surface them.
create or replace function public.sms_inbox(p_client_id uuid, p_limit int default 100)
returns table (
  id           bigint,
  contact_id   bigint,
  contact_name text,
  peer_number  text,
  body         text,
  created_at   timestamptz,
  read_at      timestamptz,
  opted_out    boolean
)
language sql stable security definer set search_path to 'public'
as $$
  select m.id, m.contact_id,
         nullif(btrim(coalesce(c.first_name, '') || ' ' || coalesce(c.last_name, '')), ''),
         m.peer_number, m.body, m.created_at, m.read_at,
         exists (select 1 from public.sms_opt_outs o where o.phone = m.peer_number)
  from public.sms_messages m
  left join public.property_crm_contacts c on c.id = m.contact_id
  where m.direction = 'inbound'
    and m.client_id = p_client_id
    and m.client_id in (select cu.client_id from public.client_users cu where cu.user_id = auth.uid())
  order by m.created_at desc
  limit least(coalesce(p_limit, 100), 500);
$$;

revoke execute on function public.sms_inbox(uuid, int) from public, anon;
grant execute on function public.sms_inbox(uuid, int) to authenticated;

-- Drives the header badge. Counts unread inbound for one client.
create or replace function public.sms_unread_count(p_client_id uuid)
returns int
language sql stable security definer set search_path to 'public'
as $$
  select count(*)::int
  from public.sms_messages m
  where m.direction = 'inbound'
    and m.read_at is null
    and m.client_id = p_client_id
    and m.client_id in (select cu.client_id from public.client_users cu where cu.user_id = auth.uid());
$$;

revoke execute on function public.sms_unread_count(uuid) from public, anon;
grant execute on function public.sms_unread_count(uuid) to authenticated;

-- Marking read is a write to sms_messages, which members cannot write directly (every other
-- write goes through a SECURITY DEFINER function for the same reason). Membership-gated:
-- ids from another tenant are silently not updated rather than erroring, because the caller
-- has no business learning whether they exist.
create or replace function public.sms_mark_read(p_ids bigint[])
returns int
language plpgsql security definer set search_path to 'public'
as $$
declare v_n int;
begin
  update public.sms_messages m
  set read_at = now()
  where m.id = any(coalesce(p_ids, '{}'::bigint[]))
    and m.direction = 'inbound'
    and m.read_at is null
    and m.client_id in (select cu.client_id from public.client_users cu where cu.user_id = auth.uid());
  get diagnostics v_n = row_count;
  return v_n;
end;
$$;

revoke execute on function public.sms_mark_read(bigint[]) from public, anon;
grant execute on function public.sms_mark_read(bigint[]) to authenticated;

-- Marks every inbound message from one number read, across contacts. The thread view uses
-- this: the operator read the conversation, not a list of row ids, and a number shared by
-- four contacts should not stay "unread" on three of them.
create or replace function public.sms_mark_thread_read(p_phone text)
returns int
language plpgsql security definer set search_path to 'public'
as $$
declare v_n int;
begin
  update public.sms_messages m
  set read_at = now()
  where m.peer_number = public.sms_digits(p_phone)
    and m.direction = 'inbound'
    and m.read_at is null
    and m.client_id in (select cu.client_id from public.client_users cu where cu.user_id = auth.uid());
  get diagnostics v_n = row_count;
  return v_n;
end;
$$;

revoke execute on function public.sms_mark_thread_read(text) from public, anon;
grant execute on function public.sms_mark_thread_read(text) to authenticated;

commit;

begin;

-- ── 6. The HELP auto-reply's write path ────────────────────────────────────────
-- This cannot go through sms_record_outbound(): that function demands a member user id and
-- raises without one, which is right for a human send and wrong for a machine one. This is
-- the only outbound path with sent_by null, which is also how the once-per-day guard in
-- sms_record_inbound() recognises an auto-reply.
--
-- service_role only. Called from sms-inbound — the one publicly reachable function — and
-- only after that function has verified the Telnyx Ed25519 signature.
create or replace function public.sms_record_help_reply(
  p_peer text, p_from text, p_body text, p_sid text
)
returns bigint
language plpgsql security definer set search_path to 'public'
as $$
declare v_id bigint; v_client uuid; v_peer text := public.sms_digits(p_peer);
begin
  select cl.id into v_client from public.clients cl
  where public.sms_digits(cl.sms_number) = public.sms_digits(p_from) limit 1;
  if v_client is null then return null; end if;

  -- Belt and braces: never auto-reply into a suppressed number even if the caller asked.
  if exists (select 1 from public.sms_opt_outs o where o.phone = v_peer) then return null; end if;

  insert into public.sms_messages (
    client_id, contact_id, direction, peer_number, from_number, to_number,
    body, provider_sid, status, sent_by
  )
  select v_client,
         (select c.id from public.property_crm_contacts c
          where c.client_id = v_client
            and exists (select 1 from jsonb_array_elements_text(coalesce(c.phones,'[]'::jsonb)) p
                        where public.sms_digits(p) = v_peer)
          order by c.updated_at desc nulls last limit 1),
         'outbound', v_peer, public.sms_digits(p_from), v_peer,
         p_body, p_sid, 'sent', null
  on conflict (provider_sid) do nothing
  returning id into v_id;

  return v_id;
end;
$$;

revoke execute on function public.sms_record_help_reply(text, text, text, text) from public, anon, authenticated;

-- ── 7. Re-revoke sms_record_inbound ────────────────────────────────────────────
-- DROP FUNCTION + CREATE re-grants EXECUTE to PUBLIC by default, which silently undid the
-- revoke from db/20260827_sms.sql. sms_record_inbound writes opt-outs and inserts into
-- sms_messages as SECURITY DEFINER; reachable by anon it would let anyone holding the
-- public bundle's key forge a reply into a tenant's thread, or forge a STOP.
--
-- Generalisable lesson, and the second of its kind in this codebase (see the "TO public"
-- note in the Tier 1 backlog): REPLACING a function preserves its grants, RECREATING it
-- does not. Any migration that drops and recreates a SECURITY DEFINER function must
-- re-issue the revoke, and should be checked with has_function_privilege afterwards.
revoke execute on function public.sms_record_inbound(text, text, text, text) from public, anon, authenticated;

commit;

-- ── Verification ───────────────────────────────────────────────────────────────
-- STOP corpus. Run after any edit to sms_is_stop(); it must return zero rows. The false
-- positives at the bottom are the ones that actually threaten this business: "stop by the
-- property" is a sentence land owners really send.
--
-- with cases(body, want) as (values
--   ('STOP', true), ('Stop.', true), ('STOP ALL', true), ('unsubscribe', true),
--   ('please stop.', true), ('ok stop', true), ('stop it', true),
--   ('please stop texting me', true), ('quit texting me', true),
--   ('remove me', true), ('Remove me from your list', true),
--   ('take my number off your list', true), ('take me off', true),
--   ('delete my number', true), ('do not text me', true), ('dont contact me', true),
--   ('don''t text me again', true), ('never contact me again', true),
--   ('no more texts', true), ('leave me alone', true), ('lose my number', true),
--   ('wrong number', true), ('Wrong #', true), ('not interested', true),
--   ('stop bothering me', true), ('opt me out please', true), ('cancel', true),
--   ('You can stop by the property any time', false),
--   ('Feel free to stop by this weekend', false),
--   ('I will stop over tomorrow to look at it', false),
--   ('Yes I am interested', false), ('How much are you offering?', false),
--   ('Call me at 8am', false), ('I already sold it', false),
--   ('Sure, send me the info', false), ('That is the wrong parcel number', false)
-- )
-- select body, want, public.sms_is_stop(body) as got
-- from cases where public.sms_is_stop(body) <> want;
--
-- Grants. Every write-path function must be service_role only; anon must reach nothing.
--
-- select p.proname,
--        has_function_privilege('anon', p.oid, 'EXECUTE') as anon,
--        has_function_privilege('authenticated', p.oid, 'EXECUTE') as authed
-- from pg_proc p join pg_namespace n on n.oid = p.pronamespace
-- where n.nspname = 'public' and p.proname like 'sms%' order by 1;
--
-- Expected: anon false everywhere; authed false for sms_record_inbound,
-- sms_record_outbound, sms_record_help_reply, sms_send_precheck, sms_update_status.
